### ISSUE TITLE
checkVisibility() in iOS < 17.4

### ISSUE THREAD

**Issue by olssonm** [panphp/pan#24]
The checkVisibility()-method was added as recently as in iOS 17.4 (2024-03-05 according to MDN), which means that all iPhone users that doesn't run the latest iOS17 (or 18 of course) will encounter `checkVisibility is not a function` via https://github.com/panphp/pan/blob/main/resources/js/src/main.ts#L138-L140

``` js
if (! element.checkVisibility()) {
     return;
}
```

Correct me if I'm wrong, but couldn't/shouldn't this just be changed to:

``` js
if (! element.checkVisibility) {
     return;
}
```

Logged a couple of hundred errors in Sentry the past day 😅

**Comment by nunomaduro** [comment]
@ryangjchandler can you fix this?

**Comment by ryangjchandler** [comment]
@nunomaduro Yep, will do a PR this evening 👍
