### ISSUE TITLE
New analytics when add new [data-pan] to link  not showing!

### ISSUE THREAD

**Issue by ahmadalnaib** [panphp/pan#33]
When add new data-pan to new button or link the analytics not show it
and i don't want make [php artisan pan:flush] to remove all data!

**Comment by pxpm** [comment]
Is your application using a whitelist for analytics ? Maybe you also need to add your new analytic there: https://github.com/panphp/pan?tab=readme-ov-file#whitelist-your-product-analytics

**Comment by ahmadalnaib** [comment]
> Is your application using a whitelist for analytics ? Maybe you also need to add your new analytic there: https://github.com/panphp/pan?tab=readme-ov-file#whitelist-your-product-analytics
Hi @pxpm  
Just add        PanConfiguration::unlimitedAnalytics(); to AppServiceProvider

**Comment by ahmadalnaib** [comment]
Just add PanConfiguration::unlimitedAnalytics(); to AppServiceProvider
